name: challenge_nera
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  scroll_to_index: ^1.0.6
  flutter_xlider: ^3.4.0
  flutter_card_swipper: ^0.4.0
  flutter_neumorphic: ^3.1.0
  flutter_svg: ^0.21.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/icon/
    - assets/icons/
    - assets/gifs/google/
    - assets/gifs/cat/
    - assets/gifs/loading/
    - assets/ui_icons/svg/
    - assets/miscellaneous/svg/
    - assets/mewnu/icons/
    - assets/mewnu/svgs/
    - assets/purple/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
    - family: Secular_One
      fonts:
        - asset: assets/fonts/Secular_One/SecularOne-Regular.ttf
    - family: Baloo_Bhai_2
      fonts:
        - asset: assets/fonts/Baloo_Bhai_2/BalooBhai2-Regular.ttf
    - family: Bellota_Text
      fonts:
        - asset: assets/fonts/Bellota_Text/BellotaText-Regular.ttf
    - family: Goldman
      fonts:
        - asset: assets/fonts/Goldman/Goldman-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar/Lalezar-Regular.ttf
    - family: Lexend_Zetta
      fonts:
        - asset: assets/fonts/Lexend_Zetta/LexendZetta-Regular.ttf
    - family: Major_Mono_Display
      fonts:
        - asset: assets/fonts/Major_Mono_Display/MajorMonoDisplay-Regular.ttf
    - family: Exo_2
      fonts:
        - asset: assets/fonts/Exo_2/Exo2-VariableFont_wght.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
